language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
services:
- postgresql
before_install:
- npm cache verify
before_script:
- cat .env.travis >> .env
- psql -c "DROP DATABASE travis;" -U postgres
- psql -c "CREATE DATABASE travis;" -U postgres
- psql -c "CREATE USER root WITH PASSWORD 'password';" -U postgres
after_success:
- npm test
branches:
  only:
  - master
  - staging
deploy:
  provider: heroku
  api_key:
    secure: RfJUhKev1qRUXGjWLEf5sptwSmtXQYnsHuHLnZnTqugas7K0n31ujZ9sFODGg5gBhMlQj8t+RkUuXqZac5OUHNtAxsu6sVdT6jBAUOY9BmuSfb4f6AsXRPsW2x5C4Lee5bYYUby698moIKa6DfL5/nZlHcxR4/wCddzgMg/JUM+/kVdFdlAKTqUgeAHue5kTKQEa4QPQoxq6hLc47nqnfBIPEXvkQheXeVtV/fehiiQntLCyTZXvKPwKpw28orIdBY3sH59psVVTDh/dFrpnnyq58sKMfZQxpABQUA9ts/N030U0sSvucL94m8AACntFDp3TMVom42pUyIBr4Rc2j8RWVQaCu44kCDeNOMIS6lMCbuTbxKirmPoeKzwRGEpfRrkVH6QA+gNpiZLxJaY4FESuE0zbHf0dE5p/vM+PKAiV1ARhMTj7/2ebFnE7siMd2PFGzIkSw/p5BSCdTaDdty2rhBgWxPMDlvWUDWO/diLkl7pKgnegoDVvNQ1OPyqCd8jiyd+4eNPuAtFlxXpAx8zWWw9AWiylc+zpAa1oI6tUgNQN1vHsTrTlpMc/EerkmuobONDHgOuCnFK/yz7dmJm6H0obud6Gdg/knVuOyxNVq6AnKm0BT8utMZRAWRsFw3XYMkj6olRvrGTDrfw4kpxP8bMH+3M4G4d/JhcSffM=
  on: master
  app: venue-app
