language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
services:
- postgresql
before_install:
- npm cache verify
before_script:
- cat .env.travis >> .env
- psql -c "DROP DATABASE travis;" -U postgres
- psql -c "CREATE DATABASE travis;" -U postgres
- psql -c "CREATE USER root WITH PASSWORD 'password';" -U postgres
branches:
  only:
  - master
  - staging
deploy:
  provider: heroku
  api_key:
    secure: i3PTdgX3yr2YYv6MEMqIbdWU8YBRA7NBiu3NxU6czfO/lxwdwkKUZB1dwJyf2AvobILiP4vZAwuOhPdkfqyE27yn/L9IHvSWX6KeKKP0OXP/CREgUSPFqjjfHZGp1JNtVcFd9fQUfDWKkkcgD4rsm9usHQzQKz1Ck0SXq5RHZeyg6aoY/HlHcG/bBziSqqwN1Mw1xrOYd883pavKkh7qirYdFel0Sw1rF0zkN3EaLQGpVwUdQkreODo94ka+FAmQ5geiF8NuNK3NYpGQv/KiEHendoI/+kx01G7YYYYUCIctRKfqh1c3Sa1ymIX7P5Z0NILHDJzV2xLM5QjLK1Jjz98pEkNpgwxwNyt0iGNFsa0uEO43Scej+00iSFK+098SSivzLdVum2Rs34XK1C3zJSQrkN1qhPESDDZ7S/FqF6gK80y6ZtCzSTjz6cc16WYCYJ6LTUUrvhrqruR2EOr8xY/8hPTLCFGpX652/fdNln/wAzcFo0wQdB1ylECJrVRYlWd4MDhuS6UGS98342vJ6mX6mREMAwfqmtXUciG97gsduA8b48wnJLzqVrgL2j6PixafIysFrqw7sXD74GCMZZmOnkMgOI6FGkOg9iR9oQRKIxdP6JP86iI1xTBdvFQJPpUbi10pwejmcmoyTDFordD7oJwDJihgB4moQNHe258=
  app: venue-app
  on:
    repo: timzprof/Venue-BackEnd
    branch: master
